### PR TITLE
Add a documentor card

### PR DESCRIPTION
**Pull request by eojthebrave**
This adds a documentor card, per https://www.drupal.org/node/2350575

This only contains the English version and not a Spanish version.

### CODE REVIEW

**Comment by DavidHernandez** [comment]
Sorry, I created another PR before noticing this one: https://github.com/drupal-mentoring/drupal-contributor-roles/pull/9

Mine includes english and spanish versions.

**Comment by penyaskito** [comment]
Looks like this doesn't have the latest revision at https://www.drupal.org/node/2350575.
@eojthebrave Could you update it?
or @DavidHernandez Could you tweak it and do a PR with @eojthebrave commit included, so we can give proper attribution?

**Comment by kattekrab** [comment]
I also had a tweak to add @eojthebrave's PR
https://github.com/eojthebrave/drupal-contributor-roles/pull/1

**Comment by penyaskito** [comment]
@kattekrab That change was included in @DavidHernandez PR, but sadly we missed attribution. I owe you one :+1: Thanks!

**Pull request merged**
