### PR TITLE
Use more common Latam terminology

### PR DESCRIPTION
**Pull request by gvso**
I just add some changes using terminology that are more common for this region

### CODE REVIEW

**Comment by penyaskito** [comment]
Discussed this one with @GVSO on IRC. Looks like they are localisms, and we should try to keep it neutral when possible, and noone else complained about those. In case of "core" I prefer it untranslated, but @jedihe has translated it.

I would like to hear opinion from @jedihe about the whole PR, but IMHO we should not merge this one.

**Comment by jedihe** [comment]
@penyaskito: they definitely sound as localisms to me. Funny thing is some places here in Colombia do use that style. I'm guessing this is why I've seen Firefox offering a specific locale for Argentina and Chile than for other countries in South America.

I'm OK with reverting my change to "core", in order to keep it unstranslated. As for the other parts, I prefer not to take them in.

**Comment by penyaskito** [comment]
We are going to freeze the translation in some hours. Can we have a separate PR with that?

**Comment by penyaskito** [comment]
OK, I did that change myself. Thanks @GVSO and @jedihe for helping with this, really appreciated!

**Pull request closed without merging**
